In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tensorflow as tf
import matplotlib.pyplot as plt
import cv2 as cv
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from tensorflow.keras import datasets,layers,Sequential
from tensorflow.keras.layers import Conv2D,MaxPooling2D,Dense,Flatten,Dropout,GlobalAveragePooling2D
from zipfile import ZipFile
import os,glob
from tqdm._tqdm_notebook import tqdm_notebook as tqdm
from keras.models import Model
from sklearn import preprocessing
from keras.layers import BatchNormalization
from zipfile import ZipFile

In [ ]:
from tensorflow.keras.applications.vgg16 import VGG16 , preprocess_input
from tensorflow.keras.preprocessing.image import load_img , img_to_array
from tensorflow.keras.models import Model

# **Team Members:**

>**Azaan Nabi Khan**

> **Asadullah Khan**

> **Muhammad Arif**







In [ ]:
file = "/content/Round1_A.zip"
with ZipFile(file,'r') as zip:
  zip.extractall()
  print('Done')

Done


In [ ]:
import shutil


files = os.listdir('/content')

destination_folder = '/content/Round_1_AI/'

if not os.path.exists(destination_folder):
    os.makedirs(destination_folder)

for file_name in files:
    if file_name.endswith('.jpg'):
        source_path = os.path.join('/content', file_name)
        shutil.move(source_path, destination_folder)


# **Feature Extraction using VGG16:**

In [ ]:
model_vgg16 = VGG16()
model_vgg16 = Model(inputs=model_vgg16.inputs,outputs=model_vgg16.layers[-2].output)
model_vgg16.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_6 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0   

In [ ]:
features_vgg16 = {}
dirc = "Round_1_AI/"
for img in os.listdir(dirc):
  img_path = dirc+img
  image = load_img(img_path,target_size=(224,224))
  image = img_to_array(image)
  image = image.reshape((1,image.shape[0],image.shape[1],image.shape[2]))
  image = preprocess_input(image)
  feature_vgg = model_vgg16.predict(image)
  features_vgg16[img] = feature_vgg


1/1 [==============================] - 1s 560ms/step


In [ ]:
features_vgg16['001.jpg']

array([[0.        , 0.21379492, 0.        , ..., 0.75152713, 1.7245815 ,
        0.        ]], dtype=float32)

# **Feature Extraction using Resnet:**

In [ ]:
from tensorflow.keras.applications.resnet50 import ResNet50

In [ ]:
model_resnet = ResNet50(weights='imagenet', include_top=False, pooling='avg')
model_resnet.summary()

Model: "resnet50"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_7 (InputLayer)        [(None, None, None, 3)]      0         []                            
                                                                                                  
 conv1_pad (ZeroPadding2D)   (None, None, None, 3)        0         ['input_7[0][0]']             
                                                                                                  
 conv1_conv (Conv2D)         (None, None, None, 64)       9472      ['conv1_pad[0][0]']           
                                                                                                  
 conv1_bn (BatchNormalizati  (None, None, None, 64)       256       ['conv1_conv[0][0]']          
 on)                                                                                       

In [ ]:
features_resnet = {}
dirc = "Round_1_AI/"
for img in os.listdir(dirc):
  img_path = dirc+img
  image = load_img(img_path,target_size=(224,224))
  image = img_to_array(image)
  image = image.reshape((1,image.shape[0],image.shape[1],image.shape[2]))
  image = preprocess_input(image)
  feature_resnet = model_resnet.predict(image)
  features_resnet[img] = feature_resnet

1/1 [==============================] - 0s 184ms/step


In [ ]:
features_resnet['001.jpg']

array([[3.587137  , 2.7993832 , 0.8236144 , ..., 0.        , 0.38131768,
        0.15879175]], dtype=float32)

# **Feature Extraction using Inception:**

In [ ]:
from tensorflow.keras.applications.inception_v3 import InceptionV3

In [ ]:
model_inception = InceptionV3(weights='imagenet', include_top=False, pooling='avg')
model_inception.summary()

Model: "inception_v3"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_8 (InputLayer)        [(None, None, None, 3)]      0         []                            
                                                                                                  
 conv2d_94 (Conv2D)          (None, None, None, 32)       864       ['input_8[0][0]']             
                                                                                                  
 batch_normalization_94 (Ba  (None, None, None, 32)       96        ['conv2d_94[0][0]']           
 tchNormalization)                                                                                
                                                                                                  
 activation_94 (Activation)  (None, None, None, 32)       0         ['batch_normalizati

In [ ]:
features_inception = {}
dirc = "Round_1_AI/"
for img in os.listdir(dirc):
  img_path = dirc+img
  image = load_img(img_path,target_size=(224,224))
  image = img_to_array(image)
  image = image.reshape((1,image.shape[0],image.shape[1],image.shape[2]))
  image = preprocess_input(image)
  feature_inception = model_inception.predict(image)
  features_inception[img] = feature_inception

1/1 [==============================] - 0s 155ms/step


In [ ]:
features_inception['001.jpg']

array([[4.4319973, 1.6724019, 2.1016757, ..., 0.       , 0.       ,
        0.       ]], dtype=float32)

# **Feature Extraction using DenseNet:**

In [ ]:
from tensorflow.keras.applications.densenet import DenseNet121

In [ ]:
model_dense = DenseNet121(weights='imagenet', include_top=False, pooling='avg')
model_dense.summary()

29084464/29084464 [==============================] - 2s 0us/step
Model: "densenet121"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_9 (InputLayer)        [(None, None, None, 3)]      0         []                            
                                                                                                  
 zero_padding2d (ZeroPaddin  (None, None, None, 3)        0         ['input_9[0][0]']             
 g2D)                                                                                             
                                                                                                  
 conv1/conv (Conv2D)         (None, None, None, 64)       9408      ['zero_padding2d[0][0]']      
                                                                                                  
 conv1/bn (BatchNormali

In [ ]:
features_Dense = {}
dirc = "Round_1_AI/"
for img in os.listdir(dirc):
  img_path = dirc+img
  image = load_img(img_path,target_size=(224,224))
  image = img_to_array(image)
  image = image.reshape((1,image.shape[0],image.shape[1],image.shape[2]))
  image = preprocess_input(image)
  feature_Dense = model_dense.predict(image)
  features_Dense[img] = feature_Dense

1/1 [==============================] - 0s 153ms/step


In [ ]:
features_Dense

{'006.jpg': array([[8.4997894e-04, 9.9842774e-04, 4.0451265e-03, ..., 1.7385690e+00,
         2.7804422e+00, 1.6485450e-01]], dtype=float32),
 '004.jpg': array([[1.9800168e-04, 2.5782608e-03, 2.6962957e-03, ..., 9.9449009e-01,
         1.6364588e+00, 6.5301812e-01]], dtype=float32),
 '002.jpg': array([[9.0057979e-04, 3.2307485e-03, 9.7922590e-03, ..., 4.6767964e+00,
         1.9925785e+00, 1.9634975e+00]], dtype=float32),
 '101.jpg': array([[7.1824739e-05, 9.3504175e-05, 9.9135255e-03, ..., 0.0000000e+00,
         3.9907310e+00, 2.6834660e+00]], dtype=float32),
 '001.jpg': array([[1.3782708e-03, 1.1079411e-03, 1.0962056e-02, ..., 3.8839426e+00,
         1.2194854e+00, 1.7513107e+00]], dtype=float32),
 '005.jpg': array([[2.5428401e-04, 1.7850945e-03, 2.7800445e-03, ..., 2.1829879e+00,
         2.3822649e+00, 1.7450003e-01]], dtype=float32),
 '103.jpg': array([[6.9536583e-04, 3.7949814e-03, 2.4490226e-03, ..., 8.6970067e-01,
         4.2059588e+00, 8.5021034e-03]], dtype=float32),
 '108.

# **Creating the CSV File for submission:**

In [ ]:
l = ['feature_'+ str(i) for i in range (1,1025)]
l1 = ['image_name']
l1.extend(l)
features_Dense_reshaped = {k: v.reshape((1, -1))[0] for k, v in features_Dense.items()}
final_sub = pd.DataFrame.from_dict(features_Dense_reshaped, orient='index')
final_sub.reset_index(inplace=True)
final_sub.columns = l1
final_sub.head()

image_name  feature_1  feature_2  feature_3  feature_4  feature_5  \
0    006.jpg   0.000850   0.000998   0.004045   0.019743   0.000000   
1    004.jpg   0.000198   0.002578   0.002696   0.006525   0.000000   
2    002.jpg   0.000901   0.003231   0.009792   0.019543   0.005425   
3    101.jpg   0.000072   0.000094   0.009914   0.020438   0.003737   
4    001.jpg   0.001378   0.001108   0.010962   0.022342   0.000341   

   feature_6  feature_7  feature_8  feature_9  ...  feature_1015  \
0   1.097867   0.001961   0.029552   0.144089  ...      2.940448   
1   0.718720   0.001394   0.014923   0.076606  ...      0.443150   
2   3.171877   0.001857   0.025682   0.033366  ...      0.936032   
3   3.255157   0.002413   0.023125   0.000000  ...      1.225376   
4   4.484272   0.001366   0.032257   0.053327  ...      0.723935   

   feature_1016  feature_1017  feature_1018  feature_1019  feature_1020  \
0      0.891119      2.413847      0.000000      1.254156      3.607356   
1      0.957206      0.726027      0.966281      0.502960      1.912375   
2      1.071504      0.043280      0.871431      0.549758      2.627153   
3      1.780402      1.791410      0.139478      0.747994      1.647487   
4      0.458957      0.251655      0.613475      0.790887      1.396729   

   feature_1021  feature_1022  feature_1023  feature_1024  
0      0.462520      1.738569      2.780442      0.164854  
1      0.009084      0.994490      1.636459      0.653018  
2      0.045430      4.676796      1.992579      1.963498  
3      1.230427      0.000000      3.990731      2.683466  
4      0.041706      3.883943      1.219485      1.751311  

[5 rows x 1025 columns]

In [ ]:
features_Dense['001.jpg']

array([[1.3782708e-03, 1.1079411e-03, 1.0962056e-02, ..., 3.8839426e+00,
        1.2194854e+00, 1.7513107e+00]], dtype=float32)

In [ ]:
final_sub.to_csv('/content/Round_1.csv',index=False)